INSERT INTO `user` (name, username, password) 
VALUES
('Adam Smith', 'asmith', 'pass123'),
('Brenda Lee', 'blee', 'pass123'),
('Charlie Brown', 'cbrown', 'pass123'),
('David Wang', 'dwang', 'pass123'),
('Emily Davis', 'edavis', 'pass123'),
('Frank Johnson', 'fjohnson', 'pass123'),
('Grace Kim', 'gkim', 'pass123'),
('Henry Park', 'hpark', 'pass123'),
('Isabel Chen', 'ichen', 'pass123'),
('Jackie Ng', 'jng', 'pass123'),
('Kevin Lee', 'klee', 'pass123'),
('Linda Wong', 'lwong', 'pass123'),
('Mark Chen', 'mchen', 'pass123'),
('Nathan Lee', 'nlee', 'pass123'),
('Olivia Kim', 'okim', 'pass123'),
('Pauline Chang', 'pchang', 'pass123'),
('Quincy Liu', 'qliu', 'pass123'),
('Rachel Zhang', 'rzhang', 'pass123'),
('Stephen Chen', 'schen', 'pass123'),
('Tina Wu', 'twu', 'pass123'),
('Ulysses Kim', 'ukim', 'pass123'),
('Victor Wong', 'vwong', 'pass123'),
('William Huang', 'whuang', 'pass123'),
('Xavier Chen', 'xchen', 'pass123'),
('Yvonne Lee', 'ylee', 'pass123'),
('Zoe Tan', 'ztan', 'pass123');
